config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'prix', to: 'pages#prix'
  get 'prix2017', to: 'pages#prix2017'
  get 'prix2018', to: 'pages#prix2018'
  get 'contact', to: 'pages#contact'
  get 'equipe', to: 'pages#equipe'
  get 'avocatconnecte', to: 'pages#avocatconnecte'
  get 'radio', to: 'pages#radio'
  get 'digest', to: 'pages#digest'
  get 'cookies', to: 'pages#cookies'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def prix
  end

  def prix2017
  end

  def prix2018
  end

  def contact
  end

  def equipe
  end

  def avocatconnecte
  end

  def radio
  end

  def digest
  end

  def cookies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Incubateur Avocats.be</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Incubateur</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag "inc1.png"%>

    <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="6ae9f5da-7903-4b77-9b13-062405cc49d9" type="text/javascript" data-blockingmode="auto"></script>
    
    <% if Rails.env.production? %>
        <script type="text/plain" data-cookieconsent="statistics">
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-90727113-2', 'auto');
          ga('send', 'pageview');

        </script>
    <% end %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_candidatures-ouvertes.html.erb
<!-- .home.html.erb Alert-->
<div class="alert alert-warning">
  <h4>Les candidatures pour les Prix de l'innovation sont ouvertes ! Rendez-vous <%= link_to "ici", prix_path %> pour déposer un dossier.</h4>
</div>

<!-- .prix.html.erb CANDIDATURES OUVERTES -->

<div class="container title text-center candidatures-ouvertes">
  <div class="row">
    <div class="col-xs-12">
      <h2>Les candidatures sont maintenant clôturées !</h2>
      <h3>Nous analysons les dossiers en recontacterons prochainements les LegalTech et avocats participants.</h3>
    </div>
  </div> <!-- .row -->
</div> <!-- .container .equipe -->


<!-- .prix.html.erb CANIDATURES OUVERTES -->

<div class="container title text-center candidatures-ouvertes">
  <div class="row">
    <div class="col-xs-12">
      <h2>Les candidatures sont maintenant ouvertes !</h2>
      <h3>Clôture de la remise des dossiers<br>le <b>mercredi 30 octobre 2019</b> à minuit</h3>
      <p>Veuillez télécharger le dossier de candidature correspondant à votre catégorie (LegalTech ou Avocat) et le renvoyer dûment complété par email à <span>incubateur@avocats.be</span> avant la date de clôture.</p>
    </div>
  </div> <!-- .row -->
</div> <!-- .container .equipe -->


<div class="container title text-center">
  <div class="row">
    <div class="col-md-offset-2 col-md-3 col-xs-12">
      <div class="download-btn">
        <%= link_to "https://drive.google.com/file/d/1czFKkCW1QHZCApXs0QChPVwaFCmN4k14/view?usp=sharing", target: "_blank" do %>
          <i class="fa fa-rocket" aria-hidden="true"></i>
          <p>Télécharger<br>Dossier de candidature<br>LegalTech</p>
        <% end %>
      </div> <!-- .download-btn -->
    </div>
    <div class="col-md-offset-2 col-md-3 col-xs-12">
      <div class="download-btn download-btn-green">
        <%= link_to "https://drive.google.com/file/d/1S1OG6WBut6X41IgxyzTFe_1Q-ZSnI77l/view?usp=sharing", target: "_blank" do %>
          <i class="fa fa-gavel" aria-hidden="true"></i>
          <p>Télécharger<br>Dossier de candidature<br>Avocat</p>
        <% end %>
      </div> <!-- .download-btn -->
    </div>
  </div> <!-- .row -->
</div> <!-- .container .equipe -->

app/views/pages/_contacts.html.erb
<!-- Contacts -->

<div class="contacts text-center">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="contacts-content">
					<h2 class="lined">Contacts</h2>
					<div class="row">
						<div class="col-md-offset-3 col-md-6 col-xs-12">
							<%= image_tag "transmutations.jpg", id: "transmutations-photo" %>
							<h4>ASBL Trans-mutation</h4>
							<h4>Avenue de la Tenderie 64 - 1170 Bruxelles</h4>
							<h4>TVA : BE 0825.252.145 </h4>
						</div>
					</div>
					<div class="contacts-avatars">
						<div class="row">
							<div class="col-md-offset-2 col-md-4 col-xs-12">
								<div class="intervenant">
									<%= image_tag "stva.jpg", class: "img-circle img-responsive avatar" %>
									<h4>Stanislas van Wassenhove</h4>
									<p>Organisateur</p>
									<p>stva@me.com</p>
								</div>
							</div>
							<div class="col-md-4 col-xs-12">
								<div class="intervenant">
									<%= image_tag "avdb.jpg", class: "img-circle img-responsive avatar" %>
									<h4>Adrien van den Branden</h4>
									<p>Assistant</p>
									<p>avdbranden@gmail.com</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/_logos.html.erb
<!-- Logos -->

<div class="programme-logos text-center">
	<div class="container">
		<div class="row">
			<div class="programme-logos-content">
				<div class="col-md-offset-2 col-md-4 col-xs-12">
					<%= image_tag "avocats.png" %>
				</div>
				<div class="col-md-4 col-xs-12">
					<%= image_tag "transmutations.jpg" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/_membres-du-jury.html.erb
<!-- MEMBRES DU JURY AVOCAT -->

<div class="container jury-avocat text-center">
  <div class="row">
    <div class="col-xs-12 jury-titre">
      <h2>Jury catégorie LegalTech pour l'édition 2019</h2>
    </div>
  </div> <!-- .row -->
  <div class="row"> <!-- .row -->
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Vinciane</h3>
      <h3 class="jury-name">Gillet</h3>
      <%= image_tag "vgillet.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Présidente du jury, Avocate Bruxelles</h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Dimitri</h3>
      <h3 class="jury-name">De Sart</h3>
      <%= image_tag "ddesart.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Avocat Bruxelles</h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Isabelle</h3>
      <h3 class="jury-name">Ferrant</h3>
      <%= image_tag "iferrant.JPG", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Avocate Bruxelles</h3>
    </div>
  </div>
  <div class="row"> <!-- .row -->
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Luc</h3>
      <h3 class="jury-name">Oger</h3>
      <%= image_tag "loger.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Avocat Namur</h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Patrick</h3>
      <h3 class="jury-name">De Wolf</h3>
      <%= image_tag "pdewolf.png", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Avocat Bruxelles</h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Jean-François</h3>
      <h3 class="jury-name">Ledoux</h3>
      <%= image_tag "jfledoux.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Avocat Dinant</h3>
    </div>
  </div>
</div> <!-- .container .category -->

<!-- MEMBRES DU JURY AVOCAT -->

<div class="container jury-avocat text-center">
  <div class="row">
    <div class="col-xs-12 jury-titre">
      <h2>Jury catégorie Avocat pour l'édition 2019</h2>
    </div>
  </div> <!-- .row -->
  <div class="row"> <!-- .row -->
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Laurent</h3>
      <h3 class="jury-name">Hublet</h3>
      <%= image_tag "lhublet.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Président du jury, Managing Director de BeCentral</h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">François</h3>
      <h3 class="jury-name">Reyntens</h3>
      <%= image_tag "freyntens.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Consultant chez Spencer Stuart </h3>
    </div>
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Marc</h3>
      <h3 class="jury-name">Beyens</h3>
      <%= image_tag "mbeyens.png", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Président de l'Institut des Juristes d'Entreprises</h3>
    </div>
  </div>
  <div class="row"> <!-- .row -->
    <div class="col-md-4 col-xs-12 jury-card">
      <h3 class="jury-first-name">Cécile</h3>
      <h3 class="jury-name">Jabaudon</h3>
      <%= image_tag "cjabaudon.jpg", class: "img-circle img-responsive avatar" %>
      <h3 class="jury-title">Operational Director au Microsoft Innovation Centre Bruxelles</h3>
    </div>
  </div> <!-- .row -->
</div> <!-- .container .category -->

app/views/pages/_partners.html.erb
<h4>Ces partenaires nous soutiennent</h4>
<div class="row">
	<div class="col-xs-12">
		<div class="big-sponsor">
			<%= link_to image_tag("larcier.jpg", class: "img-responsive center-block"), "http://www.larciergroup.com/", target: '_blank' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="small-sponsors">
		<div class="col-md-3 col-xs-12">
			<%= link_to image_tag("secib.png"), "https://www.secib.fr/", target: '_blank' %>
		</div>
		<div class="col-md-3 col-xs-12">
			<%= link_to image_tag("eliott.png"), "http://blog.eliott-markus.com/", target: '_blank' %>
		</div>
		<div class="col-md-3 col-xs-12">
			<%= link_to image_tag("mycercle.png"), "http://www.mycercle.net/", target: '_blank' %>
		</div>
		<div class="col-md-3 col-xs-12">
			<%= link_to image_tag("ipex.jpg"), "https://www.ipexgroup.com/en/", target: '_blank' %>
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<!-- CONTACTS -->

<div class="container title text-center">
	<div class="row">
		<div class="col-xs-12">
			<h1>Contacts</h1>
		</div>
	</div> <!-- .row -->
</div> <!-- .container .contacts -->

<div class="container text-center">
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<div class="contact-desctiption lined-middle-gray">
				<h2>Contactez l'Incubateur</h2>
				<p>Incubateur d'Avocats.be</p>
				<p>65 Avenue de la Toison d'Or</p>
				<p>1060 Bruxelles</p>
				<p>incubateur@avocats.be</p>
			</div>
		</div>
	</div> <!-- .row -->
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<div class="photo-equipe">
				<%= image_tag "equipe.jpg", class: "img-responsive img-rounded" %>
			</div>
		</div>
	</div>
</div> <!-- .container -->

app/views/pages/cookies.html.erb
<div class="container title text-center">
	<div class="row">
		<div class="col-xs-12">
			<h1>Cookie Declaration</h1>
		</div>
	</div> <!-- .row -->
</div> <!-- .container -->
<script id="CookieDeclaration" src="https://consent.cookiebot.com/6ae9f5da-7903-4b77-9b13-062405cc49d9/cd.js" type="text/javascript" async></script>

app/views/pages/digest.html.erb
<!-- Eadio -->

<div class="container title text-center">
	<div class="row">
		<div class="col-xs-12">
			<h1>Digital Lawyer Digest</h1>
		</div>
	</div> <!-- .row -->
</div> <!-- .container .contacts -->

<div class="container text-center">
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-xs-12">
			<div class="radio lined-middle-gray">
				<p>L'Incubateur d'Avocats.be lance le <b>"Digital Lawyer Digest"</b> (DLD), la publication qui rassemble les meilleures contributions de l'année sur un thème lié à l'innovation et le droit.<p>
				<p>Un comité éditorial présidé par Adrien Van den Branden et composé d'Antoine Nokerman et de William-James Kettlewell (tous trois membres de l'Incubateur d'Avocats.be) a pour mission de sélectionner les contributions. Les contributions doivent respecter les critères de sélection disponibles dans le <%= link_to "Mission Statement", "https://drive.google.com/file/d/1rgK_eSrfLRoxv4fEb8RGHn6k2uwkZIwZ/view?usp=sharing", target: "_blank" %>. Elles peuvent être écrites dans les trois langues nationales (<b>français</b>, <b>néerlandais</b> et <b>allemand</b>) ainsi qu'en <b>anglais</b>.</p> 
				<p>Le Digital Lawyer Digest est publié en partenariat avec l'éditeur <%= link_to "Knops Publishing", "https://www.knopspublishing.be/", target: "_blank" %> et le site <%= link_to "Jubel.be", "https://jubel.be/", target: "_blank" %><p>
			</div>
		</div>
	</div> <!-- .row -->
	<div class="row contribution-personnelle">
		<div class="col-xs-12">
			<h2>Souhaitez-vous proposer une contribution ?</h2>
			<p>Remplissez le formulaire ci-dessous !</p>
			<%= link_to "Proposer une contribution", "https://avdbranden.typeform.com/to/ir3qEI", target: "_blank", class: "btn btn-lg btn-primary" %>
		</div>
	</div>
</div> <!-- .container -->

app/views/pages/home.html.erb
<!-- Alert-->

<!-- Main banner-->

<div class="main-banner">
  <div class="banner-content text-center">
    <h1>L'avocat au coeur de l'innovation</h1>
    <p>L'Incubateur d'Avocats.be aide les avocats à surfer la vague du digital</p>
  </div>
</div>

<!-- TODO -->

<div class="constat text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-3 col-md-6 col-xs-12">
				<h1 class="grand-format">Un constat</h1>
				<h2 class="moyen-format">La vague du digital est</h2>
			</div>
		</div> <!-- .row -->

		<!-- Constat nr -->
		<div class="row constat-content">
			<div class="col-md-offset-3 col-md-3 col-xs-12">
				<div><%= image_tag("wave.png", class: "img-circle img-responsive img-constat center-block")%></div> 
			</div>
			<div class="col-md-3 col-xs-12">	
				<div class="right-item"><h2>Irrésistible</h2></div> 
			</div>
		</div> <!-- .row -->

				<!-- Constat nr -->
		<div class="row constat-content">
			<div class="col-md-offset-3 col-md-3 col-xs-12 visible-md visible-lg visibl-xl">
				<div><h2>Intersectorielle</h2></div> 
			</div>
			<div class="col-md-3 col-xs-12">	
				<div class="right-item"><%= image_tag("setting.ico", class: "img-circle img-responsive img-constat center-block")%></div> 
			</div>
			<div class="col-xs-12 visible-sm visible-xs">
				<div><h2>Intersectorielle</h2></div> 
			</div>
		</div> <!-- .row -->

		<!-- Constat nr -->
		<div class="row constat-content">
			<div class="col-md-offset-3 col-md-3 col-xs-12">
				<div><%= image_tag("global.png", class: "img-circle img-responsive img-constat center-block")%></div> 
			</div>
			<div class="col-md-3 col-xs-12">	
				<div class="right-item"><h2>Mondiale</h2></div> 
			</div>
		</div> <!-- .row -->

	</div> <!-- .container -->
</div> <!-- .constat -->


<div class="text-center">
	<div class="container">
		<div class="row diagnostic lined-middle-gray">
			<div class="col-md-offset-2 col-md-8 col-xs-12">
				<h1 class="grand-format">Un diagnostic</h1>
				<h2 class="moyen-format">Les avocats en Belgique sont trop peu sensibilisés sur les impacts du digital sur leur profession</h2>
			</div>
		</div>
	</div> <!-- .container -->
</div> <!-- .diagnostic -->

<!-- Banner Mission -->

<div class="missions-banner">
  <div class="banner-content text-center">
    <h1>Les missions de l'Incubateur</h1>
    <p>L'Incubateur d'Avocats.be réalise trois missions principales</p>
  </div>
</div>


<!-- Title -->

<% count = 0 %>

<div class="container mission frame">

	<!-- Mission nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Diffuser la connaissance</h2>
				<p>L'Incubateur informe les avocats sur l'impact des technologies du digital sur la profession d'avocat: intelligence artificielle, dématérialisation des procédures, prédictice judiciaire, etc. Les avocats sont informés sur les nouveaux business models du droit et la manière d'appréhender les nouveaux outils technologiques dans leur pratique.</p>
			</div>
		</div>		
	</div>  <!-- .row .frame-content -->

	<!-- Mission nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Promouvoir l'innovation</h2>
				<p>L'Incubateur catalyse les forces innovatrices au sein des barreaux. L'innovation est souvent perçue comme une menace extérieure par les avocats. L'Incubateur a pour mission de mettre en lumière les opportunités apportées par la révolution digitale.</p>
			</div>
		</div>		
	</div>  <!-- .row .frame-content -->

	<!-- Mission nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Partager l'information</h2>
				<p>L'Incubateur est un projet tourné vers le monde extérieur. Il relaye l'information auprès de toute personne intéressée par le croisement entre le droit et la technologie.</p>
			</div>
		</div>		
	</div>  <!-- .row .frame-content -->

</div> <!-- .container .mission -->
		

	</div>
</div>

<div class="projects-banner">
  <div class="banner-content text-center">
    <h1>Les projets de l'Incubateur</h1>
    <p>L'Incubateur d'Avocats.be réalise des projets à l'intersection du droit et de l'innovation</p>
  </div>
</div>

<!-- Mutation -->

<% count = 0 %>

<div class="container project frame">

	<!-- project nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count light-blue"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Prix de l'Innovation</h2>
				<p>L'Incubateur organise chaque année une cérémonie de remise des Prix de l'innovation. Les Prix de l'innovation sont décernés à des projets innovants dans le domaine du droit, dans les catégories "LegalTech" et "Avocat".</p>
			</div>
		</div>	
	</div>  <!-- .row .frame-content -->
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<%= link_to "Cliquez ici pour en savoir plus", prix_path, target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
		</div>
	</div> <!-- .row .frame-btn -->

	<!-- project nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count light-blue"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Conférence sur l'Avocat Connecté</h2>
				<p>L'Incubateur organise une conférence annuelle sur l'Avocat Connecté. Les professionnels du droit, s'ils sont convaincus qu'ils doivent innover, posent souvent la question <i>« Par où commencer ?</i> ». La conférence sur l'Avocat Connecté veut donner des réponses concrètes aux avocats pour les aider dans leur transition numérique.</p>
			</div>
		</div>	
	</div>  <!-- .row .frame-content -->
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<%= link_to "Cliquez ici pour en savoir plus", avocatconnecte_path, target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
		</div>
	</div> <!-- .row .frame-btn -->

	<!-- project nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count light-blue"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Marché du droit ouvert</h2>
				<p>L'Incubateur est activement impliqué dans les réflexions sur l'établissement d'un cadre pour un marché du droit ouvert. Les avocats et les LegalTech doivent pouvoir co-exister de manière harmonieuse et notamment dans le respect des règles déontologiques applicables aux avocats.</p>
			</div>
		</div>	
	</div>  <!-- .row .frame-content -->

	<!-- project nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count light-blue"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Radio de l'Incubateur</h2>
				<p>Toutes les semaines, l’équipe de l’Incubateur publie un podcast dans lequel elle interroge des experts de divers domaines afin d’accompagner les avocats dans leur transition numérique. Les interviews couvrent quatre thématiques incontournables : la legaltech, la technologie et l’innovation, l’avocat 2.0, et enfin la déontologie.</p>
			</div>
		</div>	
	</div>  <!-- .row .frame-content -->
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<%= link_to "Cliquez ici pour écoutez la Radio de l'Incubateur", radio_path, target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
		</div>
	</div> <!-- .row .frame-btn -->

		<!-- project nr -->
	<div class="row frame-content">
		<div class="col-md-offset-2 col-md-1">
			<div class="circle frame-count light-blue"><%= count += 1 %></div>
		</div>
		<div class="col-md-7">
			<div class="frame-description">
				<h2 class="moyen-format">Point de contact pour l'innovation</h2>
				<p>L'Incubateur est un point de contact pour l'innovation dans le secteur du droit. Nos membres répondent volontiers présents à toute initiative touchant au croisement entre le droit et la technologie. N'hésitez pas à nous contacter pour voir comment nous pouvons offrir notre contribution à l'innovation juridique.</p>
			</div>
		</div>	
	</div>  <!-- .row .frame-content -->
	<div class="row">
		<div class="col-md-offset-4 col-md-4 col-xs-12">
			<%= link_to "Contactez-nous !", contact_path, target: "_blank", class: "btn btn-primary btn-lg frame-btn" %>
		</div>
	</div> <!-- .row .frame-btn -->

</div> <!-- .container .project -->
		

	</div>
</div>

app/views/shared/_navbar.html.erb
<nav role="navigation" class="navbar navbar-default navbar-fixed-top bg-faded">
    <div class="navbar-conf">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to root_path do %>
                  <%= image_tag "inc1.png", class: "img-rounded img-responsive" %>
                <% end %>
            </div>
            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Incubateur", root_path %></li>
                    <li><%= link_to "Prix de l'innovation", prix_path %></li>
                    <li><%= link_to "Avocat Connecté", avocatconnecte_path %></li>
                    <li><%= link_to "Radio", radio_path %></li>
                    <li><%= link_to "Digest", digest_path %></li>
                    <li><%= link_to "Equipe", equipe_path %></li>
                    <li><%= link_to "Contacts", contact_path %></li>
                </ul>
            </div>
        </div>
    </div>
</nav>